
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - install.greymatter.io
  resources:
  - meshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.greymatter.io
  resources:
  - meshes/finalizers
  verbs:
  - update
- apiGroups:
  - install.greymatter.io
  resources:
  - meshes/status
  verbs:
  - get
  - patch
  - update
